export const stations = [
    { id: 1, station: "Shaheed Sthal (New Bus Adda)", line: "red" },
    { id: 2, station: "Hindon River", line: "red" },
    { id: 3, station: "Arthala", line: "red" },
    { id: 4, station: "Mohan Nagar", line: "red" },
    { id: 5, station: "Shyam Park", line: "red" },
    { id: 6, station: "Major Mohit Sharma", line: "red" },
    { id: 7, station: "Raj Bagh", line: "red" },
    { id: 8, station: "Shaheed Nagar", line: "red" },
    { id: 9, station: "Dilshad Garden", line: "red" },
    { id: 10, station: "Jhil Mil", line: "red" },
    { id: 11, station: "Mansarovar Park", line: "red" },
    { id: 12, station: "Shahdara", line: "red" },
    { id: 13, station: "Welcome", line: "red", conn: "Pink" },
    { id: 14, station: "Seelampur", line: "red" },
    { id: 15, station: "Shastri Park", line: "red" },
    { id: 16, station: "Kashmere Gate", line: "red", conn: "Violet" },
    { id: 17, station: "Tis Hazari", line: "red" },
    { id: 18, station: "Pul Bangash", line: "red" },
    { id: 19, station: "Pratap Nagar", line: "red" },
    { id: 20, station: "Shastri Nagar", line: "red" },
    { id: 21, station: "Inderlok", line: "red", conn: "Green" },
    { id: 22, station: "Kanhaiya Nagar", line: "red" },
    { id: 23, station: "Keshav Puram", line: "red" },
    { id: 24, station: "Netaji Subhash Place", line: "red", conn: "Pink" },
    { id: 25, station: "Kohat Enclave", line: "red" },
    { id: 26, station: "Pitam Pura", line: "red" },
    { id: 27, station: "Rohini East", line: "red" },
    { id: 28, station: "Rohini West", line: "red" },
    { id: 29, station: "Rithala", line: "red" },
    { id: 1, station: "Samaypur Badli", line: "yellow" },
      { id: 2, station: "Rohini Sector 18-19", line: "yellow" },
      { id: 3, station: "Haiderpur Badli Mor", line: "yellow" },
      { id: 4, station: "Jahangirpuri", line: "yellow" },
      { id: 5, station: "Adarsh Nagar", line: "yellow" },
      { id: 6, station: "Azadpur", line: "yellow", conn: "Pink" },
      { id: 7, station: "Model Town", line: "yellow" },
      { id: 8, station: "Guru Tegh Bahadur Nagar", line: "yellow" },
      { id: 9, station: "Vishwavidyalaya", line: "yellow" },
      { id: 10, station: "Vidhan Sabha", line: "yellow" },
      { id: 11, station: "Civil Lines", line: "yellow" },
      { id: 12, station: "Kashmere Gate", line: "yellow", conn: "Violet" },
      { id: 13, station: "Chandni Chowk", line: "yellow", touristPlace: "Red Fort" },
      { id: 14, station: "Chawri Bazar", line: "yellow", touristPlace: "Jama Masjid" },
      { id: 15, station: "New Delhi", line: "yellow", conn: "Orange" },
      { id: 16, station: "Rajiv Chowk", line: "yellow", conn: "Blue", touristPlace: "Connaught Place" },
      { id: 17, station: "Patel Chowk", line: "yellow", touristPlace: "Jantar Mantar" },
      { id: 18, station: "Central Secretariat", line: "yellow", conn: "Violet", touristPlace: "Sansad Bhavan" },
      { id: 19, station: "Udyog Bhawan", line: "yellow", touristPlace: "Rashtrapati Bhavan" },
      { id: 20, station: "Lok Kalyan Marg", line: "yellow", touristPlace: "Lodhi Gardens" },
      { id: 21, station: "Jorbagh", line: "yellow", touristPlace: "Safdarjung Tomb" },
      { id: 22, station: "Dilli Haat INA", line: "yellow", conn: "Pink" },
      { id: 23, station: "AIIMS", line: "yellow" },
      { id: 24, station: "Green Park", line: "yellow" },
      { id: 25, station: "Hauz Khas", line: "yellow", conn: "Magenta" },
      { id: 26, station: "Malviya Nagar", line: "yellow" },
      { id: 27, station: "Saket", line: "yellow" },
      { id: 28, station: "Qutab Minar", line: "yellow", touristPlace: "Qutab Minar" },
      { id: 29, station: "Chhattarpur", line: "yellow", touristPlace: "Chhattarpur Temple" },
      { id: 30, station: "Sultanpur", line: "yellow" },
      { id: 31, station: "Ghitorni", line: "yellow" },
      { id: 32, station: "Arjan Garh", line: "yellow" },
      { id: 33, station: "Guru Dronacharya", line: "yellow" },
      { id: 34, station: "Sikandarpur", line: "yellow", conn: "Rapid" },
      { id: 35, station: "MG Road", line: "yellow" },
      { id: 36, station: "IFFCO Chowk", line: "yellow" },
      { id: 37, station: "Huda City Centre", line: "yellow" },
      { id: 1, station: "Dwarka Sector 21", conn: "Orange", line: "blue" },
    { id: 2, station: "Dwarka Sector 8", line: "blue" },
    { id: 3, station: "Dwarka Sector 9", line: "blue" },
    { id: 4, station: "Dwarka Sector 10", line: "blue" },
    { id: 5, station: "Dwarka Sector 11", line: "blue" },
    { id: 6, station: "Dwarka Sector 12", line: "blue" },
    { id: 7, station: "Dwarka Sector 13", line: "blue" },
    { id: 8, station: "Dwarka Sector 14", line: "blue" },
    { id: 9, station: "Dwarka", conn: "Gray", line: "blue" },
    { id: 10, station: "Dwarka Mor", line: "blue" },
    { id: 11, station: "Nawada", line: "blue" },
    { id: 12, station: "Uttam Nagar West", line: "blue" },
    { id: 13, station: "Uttam Nagar East", line: "blue" },
    { id: 14, station: "Janak Puri West", conn: "Magenta", line: "blue" },
    { id: 15, station: "Janak Puri East", line: "blue" },
    { id: 16, station: "Tilak Nagar", line: "blue" },
    { id: 17, station: "Subhash Nagar", line: "blue" },
    { id: 18, station: "Tagore Garden", line: "blue" },
    { id: 19, station: "Rajouri Garden", conn: "Pink", line: "blue" },
    { id: 20, station: "Ramesh Nagar", line: "blue" },
    { id: 21, station: "Moti Nagar", line: "blue" },
    { id: 22, station: "Kirti Nagar", conn: "Green", line: "blue" },
    { id: 23, station: "Shadipur", line: "blue" },
    { id: 24, station: "Patel Nagar", line: "blue" },
    { id: 25, station: "Rajendra Place", line: "blue" },
    { id: 26, station: "Karol Bagh", line: "blue" },
    { id: 27, station: "Jhandewalan", line: "blue" },
    { id: 28, station: "R K Ashram Marg", touristPlace: "Laxmi Narayan Temple", line: "blue" },
    { id: 29, station: "Rajiv Chowk", conn: "Yellow", line: "blue" },
    { id: 30, station: "Barakhamba", line: "blue" },
    { id: 31, station: "Mandi House", conn: "Violet", line: "blue" },
    { id: 32, station: "Supreme Court (Pragati Maidan)", touristPlace: "Rajghat, Shanti Vana", line: "blue" },
    { id: 33, station: "Indraprastha", touristPlace: "Purana Quila", line: "blue" },
    { id: 34, station: "Yamuna Bank", line: "blue" },
    { id: 35, station: "Akshardham", touristPlace: "Akshardham Temple", line: "blue" },
    { id: 36, station: "Mayur Vihar Phase-1", conn: "Pink", line: "blue" },
    { id: 37, station: "Mayur Vihar Extension", line: "blue" },
    { id: 38, station: "New Ashok Nagar", line: "blue" },
    { id: 39, station: "Noida Sector 15", line: "blue" },
    { id: 40, station: "Noida Sector 16", line: "blue" },
    { id: 41, station: "Noida Sector 18", line: "blue" },
    { id: 42, station: "Botanical Garden", conn: "Magenta", line: "blue" },
    { id: 43, station: "Golf Course", line: "blue" },
    { id: 44, station: "Noida City Center", line: "blue" },
    { id: 45, station: "Noida Sector 34", line: "blue" },
    { id: 46, station: "Noida Sector 52", conn: "Aqua", line: "blue" },
    { id: 47, station: "Noida Sector 61", line: "blue" },
    { id: 48, station: "Noida Sector 59", line: "blue" },
    { id: 49, station: "Noida Sector 62", line: "blue" },
    { id: 50, station: "Noida Electronic City", line: "blue" },
    { id: 1, station: "Kashmere Gate", conn: "Yellow", line: "violet" },
  { id: 2, station: "Lal Quila", line: "violet" },
  { id: 3, station: "Jama Masjid", line: "violet" },
  { id: 4, station: "Delhi Gate", line: "violet" },
  { id: 5, station: "ITO", line: "violet" },
  { id: 6, station: "Mandi House", conn: "Blue", line: "violet" },
  { id: 7, station: "Janpath", line: "violet" },
  { id: 8, station: "Central Secretariat", touristPlace: "Cathedral Church", conn: "Yellow", line: "violet" },
  { id: 9, station: "Khan Market", touristPlace: "India Gate", line: "violet" },
  { id: 10, station: "Jawaharlal Nehru Stadium", touristPlace: "Humayun Tomb, Nizamuddin Dargah, Salimgarh Fort", line: "violet" },
  { id: 11, station: "Jangpura", line: "violet" },
  { id: 12, station: "Lajpat Nagar", conn: "Pink", line: "violet" },
  { id: 13, station: "Moolchand", line: "violet" },
  { id: 14, station: "Kailash Colony", line: "violet" },
  { id: 15, station: "Nehru Place", touristPlace: "ISKCON Temple, Lotus Temple", line: "violet" },
  { id: 16, station: "Kalkaji Mandir", touristPlace: "Kalkaji Temple", conn: "Magenta", line: "violet" },
  { id: 17, station: "Govind Puri", line: "violet" },
  { id: 18, station: "Okhla", line: "violet" },
  { id: 19, station: "Jasola", line: "violet" },
  { id: 20, station: "Sarita Vihar", line: "violet" },
  { id: 21, station: "Mohan Estate", line: "violet" },
  { id: 22, station: "Tughlakabad", touristPlace: "Tughlaqabad", line: "violet" },
  { id: 23, station: "Badarpur Border", line: "violet" },
  { id: 24, station: "Sarai", line: "violet" },
  { id: 25, station: "N.H.P.C. Chowk", line: "violet" },
  { id: 26, station: "Mewala Maharajpur", line: "violet" },
  { id: 27, station: "Sector 28 Faridabad", line: "violet" },
  { id: 28, station: "Badkal Mor", line: "violet" },
  { id: 29, station: "Old Faridabad", line: "violet" },
  { id: 30, station: "Neelam Chowk Ajronda", line: "violet" },
  { id: 31, station: "Bata Chowk", line: "violet" },
  { id: 32, station: "Escorts Mujesar", line: "violet" },
  { id: 33, station: "Sant Surdas - Sihi", line: "violet" },
  { id: 34, station: "Raja Nahar Singh", line: "violet" },
  { id: 1, station: "Janak Puri West", conn: "Blue", line: "magenta" },
  { id: 2, station: "Dabri Mor - Janakpuri South", line: "magenta" },
  { id: 3, station: "Dashrath Puri", line: "magenta" },
  { id: 4, station: "Palam", line: "magenta" },
  { id: 5, station: "Sadar Bazaar Cantonment", line: "magenta" },
  { id: 6, station: "Terminal 1 IGI Airport", line: "magenta" },
  { id: 7, station: "Shankar Vihar", line: "magenta" },
  { id: 8, station: "Vasant Vihar", line: "magenta" },
  { id: 9, station: "Munirka", line: "magenta" },
  { id: 10, station: "RK Puram", line: "magenta" },
  { id: 11, station: "IIT Delhi", line: "magenta" },
  { id: 12, station: "Hauz Khas", conn: "Yellow", line: "magenta" },
  { id: 13, station: "Panchsheel Park", line: "magenta" },
  { id: 14, station: "Chirag Delhi", line: "magenta" },
  { id: 15, station: "Greater Kailash", line: "magenta" },
  { id: 16, station: "Nehru Enclave", line: "magenta" },
  { id: 17, station: "Kalkaji Mandir", conn: "Violet", line: "magenta" },
  { id: 18, station: "Okhla NSIC", line: "magenta" },
  { id: 19, station: "Sukhdev Vihar", line: "magenta" },
  { id: 20, station: "JAMIA MILLIA ISLAMIA", line: "magenta" },
  { id: 21, station: "Okhla Vihar", line: "magenta" },
  { id: 22, station: "Jasola Vihar Shaheen Bagh", line: "magenta" },
  { id: 23, station: "Kalindi Kunj", line: "magenta" },
  { id: 24, station: "Okhla Bird Sanctuary", line: "magenta" },
  { id: 25, station: "Botanical Garden", conn: "Blue", line: "magenta" },
  { id: 1, station: "Majlis Park", line: "pink" },
  { id: 2, station: "Azadpur", conn: "Yellow", line: "pink" },
  { id: 3, station: "Shalimar Bagh", line: "pink" },
  { id: 4, station: "Netaji Subash Place", conn: "Red", line: "pink" },
  { id: 5, station: "Shakurpur", line: "pink" },
  { id: 6, station: "Punjabi Bagh West", line: "pink" },
  { id: 7, station: "ESI BASAI DARAPUR", line: "pink" },
  { id: 8, station: "Rajouri Garden", conn: "Blue", line: "pink" },
  { id: 9, station: "Maya Puri", line: "pink" },
  { id: 10, station: "Naraina Vihar", line: "pink" },
  { id: 11, station: "Delhi Cantt", line: "pink" },
  { id: 12, station: "Durgabai Deshmukh South Campus", conn: "Orange", line: "pink" },
  { id: 13, station: "Sir Vishweshwaraiah Moti Bagh", line: "pink" },
  { id: 14, station: "Bhikaji Cama Place", line: "pink" },
  { id: 15, station: "Sarojini Nagar", line: "pink" },
  { id: 16, station: "Dilli Haat INA", conn: "Yellow", line: "pink" },
  { id: 17, station: "South Extension", line: "pink" },
  { id: 18, station: "Lajpat Nagar", conn: "Violet", line: "pink" },
  { id: 19, station: "Vinobapuri", line: "pink" },
  { id: 20, station: "Ashram", line: "pink" },
  { id: 21, station: "Sarai Kale Khan Hazrat Nizamuddin", line: "pink" },
  { id: 22, station: "Mayur Vihar Phase-1", conn: "Blue", line: "pink" },
  { id: 23, station: "Mayur Vihar Pocket I", line: "pink" },
  { id: 24, station: "Trilokpuri Sanjay Lake", line: "pink" },
  { id: 25, station: "Vinod Nagar East", line: "pink" },
  { id: 26, station: "Mandawali - West Vinod Nagar", line: "pink" },
  { id: 27, station: "IP Extension", line: "pink" },
  { id: 28, station: "Anand Vihar", conn: "Blue", line: "pink" },
  { id: 29, station: "Karkar Duma", conn: "Blue", line: "pink" },
  { id: 30, station: "Karkarduma Court", line: "pink" },
  { id: 31, station: "Krishna Nagar", line: "pink" },
  { id: 32, station: "East Azad Nagar", line: "pink" },
  { id: 33, station: "Welcome", conn: "Red", line: "pink" },
  { id: 34, station: "Jaffrabad", line: "pink" },
  { id: 35, station: "Maujpur", line: "pink" },
  { id: 36, station: "Gokulpuri", line: "pink" },
  { id: 37, station: "Johri Enclave", line: "pink" },
  { id: 38, station: "Shiv Vihar", line: "pink" }
]